#pragma once

#pragma comment(lib, "opencv_calib3d343.lib")
#pragma comment(lib, "opencv_core343.lib")
#pragma comment(lib, "opencv_features2d343.lib")
#pragma comment(lib, "opencv_flann343.lib")
#pragma comment(lib, "opencv_highgui343.lib")
#pragma comment(lib, "opencv_imgcodecs343.lib")
#pragma comment(lib, "opencv_imgproc343.lib")
#pragma comment(lib, "opencv_ml343.lib")
#pragma comment(lib, "opencv_objdetect343.lib")
#pragma comment(lib, "opencv_photo343.lib")
#pragma comment(lib, "opencv_shape343.lib")
#pragma comment(lib, "opencv_stitching343.lib")
#pragma comment(lib, "opencv_superres343.lib")
#pragma comment(lib, "opencv_video343.lib")
#pragma comment(lib, "opencv_videoio343.lib")
#pragma comment(lib, "opencv_videostab343.lib")
